name: Build and UNIT Test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_unit_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install Application
      run: npm install
    - name: Install required browsers for Playwright
      run: npx playwright install
    - name: Start the application
      run: npm start &
    - name: Run UNIT tests
      run: npm run test:unit
    - name: Display SoftUni username
      run: echo "netmasterbg"

  test_ui:
    runs-on: ubuntu-latest
    needs: build_unit_test
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install Application
      run: npm install
    - name: Install required browsers for Playwright
      run: npx playwright install
    - name: Start the application
      run: npm start &
    - name: Run UI tests
      run: npm run test:ui

  deploy_to_render:
    needs: test_ui
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    steps:
      - name: Deploy to production
        uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true
          github_token: ${{ secrets.GH_TOKEN }}